"""Hand-authored base scenarios for L13 stimuli_v1.

Each base yields five conditions (see DATA_AND_GOLD.md).

Field contract
--------------
sub    : the subordinate clause, tensed, used verbatim after the connective.
         "After <sub>, <main>." / "Before <sub>, <main>."
main   : the main clause, tensed, lowercase-initial, no final period.
         It must read naturally both before and after the target event, and
         must be a *plausible blocker* of the target event when it precedes it.
target : the probed proposition, a standalone sentence without final period.
         Semantically identical to `sub`; kept as its own field so the probe
         string is invariant across conditions.
plan   : non-temporal, non-committal introduction of the target event.
main_alone : the main clause as an independent sentence.
confirm: continuation asserting that the target event happened.
cancel : continuation asserting that the target event did not happen.

No pronoun is used where its referent is not fully unambiguous, and no
gendered pronoun is used for a person whose gender is not otherwise stated.
"""

BASES = [
    dict(
        id="b01",
        sub="Maya submitted the application",
        main="the portal closed",
        target="Maya submitted the application",
        plan="Maya planned to submit the application.",
        main_alone="The portal closed at midnight.",
        confirm="A staff member accepted the application by email that evening.",
        cancel="The closure was permanent, and the application was never submitted.",
    ),
    dict(
        id="b02",
        sub="Daniel boarded the train",
        main="the doors locked",
        target="Daniel boarded the train",
        plan="Daniel intended to board the train.",
        main_alone="The doors locked at 8:02.",
        confirm="A conductor released the doors again, and Daniel got on.",
        cancel="No one released the doors, and Daniel stayed on the platform.",
    ),
    dict(
        id="b03",
        sub="Lena paid the deposit",
        main="the bank froze her account",
        target="Lena paid the deposit",
        plan="Lena was expected to pay the deposit.",
        main_alone="The bank froze Lena's account that week.",
        confirm="Lena borrowed cash from a friend and paid the deposit the same day.",
        cancel="Lena could not raise the money, and the deposit went unpaid.",
    ),
    dict(
        id="b04",
        sub="Omar signed the contract",
        main="the lawyer withdrew the offer",
        target="Omar signed the contract",
        plan="Omar was preparing to sign the contract.",
        main_alone="The lawyer withdrew the offer on Tuesday.",
        confirm="The offer was reinstated the next morning, and Omar signed the contract.",
        cancel="The offer was never reinstated, and Omar did not sign the contract.",
    ),
    dict(
        id="b05",
        sub="the nurse gave the patient the injection",
        main="the supply cabinet was locked",
        target="The nurse gave the patient the injection",
        plan="The nurse was scheduled to give the patient the injection.",
        main_alone="The supply cabinet was locked overnight.",
        confirm="A colleague unlocked the cabinet, and the injection was given.",
        cancel="No one could open the cabinet, and the injection was never given.",
    ),
    dict(
        id="b06",
        sub="Priya caught the ferry",
        main="the harbour closed for the storm",
        target="Priya caught the ferry",
        plan="Priya hoped to catch the ferry.",
        main_alone="The harbour closed for the storm.",
        confirm="The harbour reopened briefly at noon, and Priya caught the ferry.",
        cancel="The harbour stayed shut all day, and Priya never caught the ferry.",
    ),
    dict(
        id="b07",
        sub="the team released the update",
        main="the build server crashed",
        target="The team released the update",
        plan="The team was getting ready to release the update.",
        main_alone="The build server crashed on Friday.",
        confirm="Engineers restored the server, and the update was released.",
        cancel="The server stayed down, and the update was never released.",
    ),
    dict(
        id="b08",
        sub="Marcus returned the library book",
        main="the branch shut down",
        target="Marcus returned the library book",
        plan="Marcus meant to return the library book.",
        main_alone="The branch shut down in March.",
        confirm="Marcus dropped the book at another branch that week.",
        cancel="Marcus never returned the library book.",
    ),
    dict(
        id="b09",
        sub="Sofia finished the marathon",
        main="the organisers stopped the race",
        target="Sofia finished the marathon",
        plan="Sofia was hoping to finish the marathon.",
        main_alone="The organisers stopped the race at the four-hour mark.",
        confirm="The remaining runners were allowed to continue, and Sofia finished the marathon.",
        cancel="The course was cleared, and Sofia did not finish the marathon.",
    ),
    dict(
        id="b10",
        sub="the journalist published the article",
        main="the editor pulled the story",
        target="The journalist published the article",
        plan="The journalist was about to publish the article.",
        main_alone="The editor pulled the story on Thursday.",
        confirm="The decision was reversed, and the article was published that night.",
        cancel="The decision stood, and the article was never published.",
    ),
    dict(
        id="b11",
        sub="Ken renewed his passport",
        main="the office moved to appointment-only service",
        target="Ken renewed his passport",
        plan="Ken needed to renew his passport.",
        main_alone="The office moved to appointment-only service in January.",
        confirm="Ken booked an appointment and renewed the passport in March.",
        cancel="Ken never got an appointment, and the passport expired unrenewed.",
    ),
    dict(
        id="b12",
        sub="the startup shipped the prototype",
        main="its main supplier went bankrupt",
        target="The startup shipped the prototype",
        plan="The startup was preparing to ship the prototype.",
        main_alone="The startup's main supplier went bankrupt in April.",
        confirm="Another supplier stepped in, and the prototype shipped in June.",
        cancel="No other supplier was found, and the prototype never shipped.",
    ),
    dict(
        id="b13",
        sub="Elena handed in her thesis",
        main="the department changed the submission rules",
        target="Elena handed in her thesis",
        plan="Elena was getting ready to hand in her thesis.",
        main_alone="The department changed the submission rules that term.",
        confirm="Elena reformatted the manuscript and handed in the thesis on Friday.",
        cancel="Elena could not meet the new rules and did not hand in the thesis.",
    ),
    dict(
        id="b14",
        sub="Rosa mailed the package",
        main="the post office ran out of customs forms",
        target="Rosa mailed the package",
        plan="Rosa wanted to mail the package.",
        main_alone="The post office ran out of customs forms.",
        confirm="New forms arrived, and Rosa mailed the package that afternoon.",
        cancel="The forms never arrived, and the package stayed on Rosa's desk.",
    ),
    dict(
        id="b15",
        sub="the committee approved the budget",
        main="two of its members resigned",
        target="The committee approved the budget",
        plan="The committee was expected to approve the budget.",
        main_alone="Two of the committee's members resigned in May.",
        confirm="Replacements were appointed, and the budget was approved.",
        cancel="The vote never took place, and the budget was not approved.",
    ),
    dict(
        id="b16",
        sub="Ahmed sold his car",
        main="the buyer's loan fell through",
        target="Ahmed sold his car",
        plan="Ahmed was trying to sell his car.",
        main_alone="The buyer's loan fell through in October.",
        confirm="Another buyer appeared, and Ahmed sold the car a week later.",
        cancel="No other buyer appeared, and Ahmed kept the car.",
    ),
    dict(
        id="b17",
        sub="Nina took the exam",
        main="the testing centre lost power",
        target="Nina took the exam",
        plan="Nina was registered to take the exam.",
        main_alone="The testing centre lost power that morning.",
        confirm="Power returned within the hour, and Nina took the exam.",
        cancel="The session was cancelled, and Nina did not take the exam.",
    ),
    dict(
        id="b18",
        sub="the crew put out the fire",
        main="the water pressure dropped",
        target="The crew put out the fire",
        plan="The crew was working to put out the fire.",
        main_alone="The water pressure dropped shortly past midnight.",
        confirm="Pressure was restored, and the crew put out the fire.",
        cancel="Pressure never returned, and the crew never put out the fire.",
    ),
    dict(
        id="b19",
        sub="Diego deleted the file",
        main="his laptop was confiscated",
        target="Diego deleted the file",
        plan="Diego was going to delete the file.",
        main_alone="Diego's laptop was confiscated on Monday.",
        confirm="The laptop was returned the next day, and Diego deleted the file.",
        cancel="The laptop was never returned, and the file stayed on the disk.",
    ),
    dict(
        id="b20",
        sub="the mayor signed the order",
        main="the court issued an injunction",
        target="The mayor signed the order",
        plan="The mayor was preparing to sign the order.",
        main_alone="The court issued an injunction that afternoon.",
        confirm="The injunction was lifted, and the mayor signed the order.",
        cancel="The injunction held, and the order was never signed.",
    ),
    dict(
        id="b21",
        sub="Yuki collected the prize",
        main="the sponsor pulled out",
        target="Yuki collected the prize",
        plan="Yuki was waiting to collect the prize.",
        main_alone="The sponsor pulled out of the competition.",
        confirm="A new sponsor took over, and Yuki collected the prize.",
        cancel="No new sponsor took over, and the prize was never paid out.",
    ),
    dict(
        id="b22",
        sub="the students staged the play",
        main="the theatre flooded",
        target="The students staged the play",
        plan="The students were rehearsing to stage the play.",
        main_alone="The theatre flooded the week of the performance.",
        confirm="A hall was found nearby, and the students staged the play.",
        cancel="No other venue was found, and the play was called off.",
    ),
    dict(
        id="b23",
        sub="Carla withdrew the cash",
        main="the cash machine went offline",
        target="Carla withdrew the cash",
        plan="Carla needed to withdraw the cash.",
        main_alone="The cash machine went offline that evening.",
        confirm="The machine came back online, and Carla withdrew the cash.",
        cancel="The machine stayed offline, and Carla went home with nothing.",
    ),
    dict(
        id="b24",
        sub="the surgeon performed the operation",
        main="the patient's fever spiked",
        target="The surgeon performed the operation",
        plan="The surgeon was scheduled to perform the operation.",
        main_alone="The patient's fever spiked overnight.",
        confirm="The fever came down, and the surgeon performed the operation that evening.",
        cancel="The fever persisted, and the operation was never performed.",
    ),
    dict(
        id="b25",
        sub="Tomas repaid the loan",
        main="the lender sold the debt",
        target="Tomas repaid the loan",
        plan="Tomas was arranging to repay the loan.",
        main_alone="The lender sold the debt to a collection agency.",
        confirm="The new holder accepted payment, and Tomas repaid the loan.",
        cancel="The account was frozen in a dispute, and the loan was not repaid.",
    ),
    dict(
        id="b26",
        sub="the village rebuilt the bridge",
        main="the funding was suspended",
        target="The village rebuilt the bridge",
        plan="The village was planning to rebuild the bridge.",
        main_alone="The funding was suspended that spring.",
        confirm="Funding resumed, and the village rebuilt the bridge that summer.",
        cancel="Funding never resumed, and the bridge was left as it was.",
    ),
    dict(
        id="b27",
        sub="Hana registered for the course",
        main="the class filled up",
        target="Hana registered for the course",
        plan="Hana wanted to register for the course.",
        main_alone="The class filled up within a day.",
        confirm="A place opened, and Hana registered for the course.",
        cancel="No place opened, and Hana did not register for the course.",
    ),
    dict(
        id="b28",
        sub="the company paid the fine",
        main="the regulator revised the amount",
        target="The company paid the fine",
        plan="The company was expected to pay the fine.",
        main_alone="The regulator revised the amount in June.",
        confirm="The revised amount was settled, and the company paid the fine.",
        cancel="The dispute continued, and the company never paid the fine.",
    ),
    dict(
        id="b29",
        sub="Ivan reached the summit",
        main="a storm moved in",
        target="Ivan reached the summit",
        plan="Ivan was climbing toward the summit.",
        main_alone="A storm moved in during the night.",
        confirm="The weather cleared by dawn, and Ivan reached the summit.",
        cancel="The team turned back, and Ivan did not reach the summit.",
    ),
    dict(
        id="b30",
        sub="Grace adopted the dog",
        main="the shelter closed for quarantine",
        target="Grace adopted the dog",
        plan="Grace was hoping to adopt the dog.",
        main_alone="The shelter closed for quarantine in February.",
        confirm="The quarantine ended, and Grace adopted the dog.",
        cancel="The dog was moved to another city, and Grace did not adopt the dog.",
    ),
    dict(
        id="b31",
        sub="the engineers fixed the leak",
        main="the tunnel was sealed",
        target="The engineers fixed the leak",
        plan="The engineers were sent to fix the leak.",
        main_alone="The tunnel was sealed for safety.",
        confirm="The tunnel was opened again, and the engineers fixed the leak.",
        cancel="The tunnel stayed sealed, and the leak was never fixed.",
    ),
    dict(
        id="b32",
        sub="Leo apologised to his sister",
        main="she left the country",
        target="Leo apologised to his sister",
        plan="Leo was thinking about apologising to his sister.",
        main_alone="Leo's sister left the country in August.",
        confirm="Leo called her abroad and apologised.",
        cancel="They never spoke again, and Leo never apologised.",
    ),
    dict(
        id="b33",
        sub="the auction house sold the painting",
        main="the owner withdrew it",
        target="The auction house sold the painting",
        plan="The auction house was preparing to sell the painting.",
        main_alone="The owner withdrew the painting from the sale.",
        confirm="The painting was relisted and sold in the autumn sale.",
        cancel="The painting was never relisted and was not sold.",
    ),
    dict(
        id="b34",
        sub="Anya finished the report",
        main="her contract ended",
        target="Anya finished the report",
        plan="Anya was working on the report.",
        main_alone="Anya's contract ended in November.",
        confirm="Anya was rehired for a week and finished the report.",
        cancel="The work passed to someone else, and Anya did not finish the report.",
    ),
    dict(
        id="b35",
        sub="the farmer harvested the wheat",
        main="hail flattened part of the field",
        target="The farmer harvested the wheat",
        plan="The farmer was about to harvest the wheat.",
        main_alone="Hail flattened part of the field in July.",
        confirm="The rest of the field was cut, and the farmer harvested the wheat.",
        cancel="The whole crop was lost, and the wheat was never harvested.",
    ),
    dict(
        id="b36",
        sub="Peter booked the flight",
        main="the airline suspended the route",
        target="Peter booked the flight",
        plan="Peter was going to book the flight.",
        main_alone="The airline suspended the route in September.",
        confirm="The route reopened, and Peter booked the flight.",
        cancel="The route stayed closed, and Peter did not book the flight.",
    ),
    dict(
        id="b37",
        sub="the council demolished the old mill",
        main="preservation status was granted",
        target="The council demolished the old mill",
        plan="The council was planning to demolish the old mill.",
        main_alone="Preservation status was granted that year.",
        confirm="The status was revoked, and the council demolished the old mill.",
        cancel="The status held, and the old mill is still standing.",
    ),
    dict(
        id="b38",
        sub="Mira had her son vaccinated",
        main="the clinic ran out of doses",
        target="Mira had her son vaccinated",
        plan="Mira wanted to have her son vaccinated.",
        main_alone="The clinic ran out of doses that month.",
        confirm="A new shipment arrived, and Mira had her son vaccinated.",
        cancel="No shipment arrived, and Mira's son was not vaccinated.",
    ),
    dict(
        id="b39",
        sub="the archivist digitised the manuscript",
        main="the reading room was closed",
        target="The archivist digitised the manuscript",
        plan="The archivist was assigned to digitise the manuscript.",
        main_alone="The reading room was closed for repairs.",
        confirm="The reading room reopened, and the archivist digitised the manuscript.",
        cancel="The reading room stayed closed, and the manuscript was never digitised.",
    ),
    dict(
        id="b40",
        sub="Ravi cancelled the subscription",
        main="the provider changed its billing system",
        target="Ravi cancelled the subscription",
        plan="Ravi meant to cancel the subscription.",
        main_alone="The provider changed its billing system in July.",
        confirm="Ravi reached an agent and cancelled the subscription.",
        cancel="Ravi never reached an agent, and the subscription stayed active.",
    ),
]
