"""Hand-authored base scenarios for L13 stimuli_v1.

Each base yields five conditions (see DATA_AND_GOLD.md).

Field contract
--------------
sub    : the subordinate clause, tensed, used verbatim after the connective.
         "After <sub>, <main>." / "Before <sub>, <main>."
main   : the main clause, tensed, lowercase-initial, no final period.
         It must read naturally both before and after the target event, and
         must be a *plausible blocker* of the target event when it precedes it.
target : the probed proposition, a standalone sentence without final period.
         Semantically identical to `sub`; kept as its own field so the probe
         string is invariant across conditions.
plan   : non-temporal, non-committal introduction of the target event.
main_alone : the main clause as an independent sentence.
confirm: continuation asserting that the target event happened.
cancel : continuation asserting that the target event did not happen.

No pronoun is used where its referent is not fully unambiguous, and no
gendered pronoun is used for a person whose gender is not otherwise stated.
"""

BASES = [
    dict(
        id="b01",
        pragmatic_bias="neutral",
        sub="Maya submitted the application",
        main="the portal closed",
        target="Maya submitted the application",
        plan="Maya planned to submit the application.",
        main_alone="The portal closed at midnight.",
        confirm="A staff member accepted the application by email that evening.",
        cancel="The closure was permanent, and the application was never submitted.",
    ),
    dict(
        id="b02",
        pragmatic_bias="no_leaning",
        sub="Daniel boarded the train",
        main="the doors locked",
        target="Daniel boarded the train",
        plan="Daniel intended to board the train.",
        main_alone="The doors locked at 8:02.",
        confirm="A conductor released the doors again, and Daniel got on.",
        cancel="No one released the doors, and Daniel stayed on the platform.",
    ),
    dict(
        id="b03",
        pragmatic_bias="neutral",
        sub="Lena paid the deposit",
        main="the bank froze her account",
        target="Lena paid the deposit",
        plan="Lena was expected to pay the deposit.",
        main_alone="The bank froze Lena's account that week.",
        confirm="Lena borrowed cash from a friend and paid the deposit the same day.",
        cancel="Lena could not raise the money, and the deposit went unpaid.",
    ),
    dict(
        id="b04",
        pragmatic_bias="neutral",
        sub="Omar signed the contract",
        main="the lawyer withdrew the offer",
        target="Omar signed the contract",
        plan="Omar was preparing to sign the contract.",
        main_alone="The lawyer withdrew the offer on Tuesday.",
        confirm="The offer was reinstated the next morning, and Omar signed the contract.",
        cancel="The offer was never reinstated, and Omar did not sign the contract.",
    ),
    dict(
        id="b05",
        pragmatic_bias="neutral",
        sub="the nurse gave the patient the injection",
        main="the supply cabinet was locked",
        target="The nurse gave the patient the injection",
        plan="The nurse was scheduled to give the patient the injection.",
        main_alone="The supply cabinet was locked overnight.",
        confirm="A colleague unlocked the cabinet, and the injection was given.",
        cancel="No one could open the cabinet, and the injection was never given.",
    ),
    dict(
        id="b06",
        pragmatic_bias="no_leaning",
        sub="Priya caught the ferry",
        main="the harbour closed for the storm",
        target="Priya caught the ferry",
        plan="Priya hoped to catch the ferry.",
        main_alone="The harbour closed for the storm.",
        confirm="The harbour reopened briefly at noon, and Priya caught the ferry.",
        cancel="The harbour stayed shut all day, and Priya never caught the ferry.",
    ),
    dict(
        id="b07",
        pragmatic_bias="yes_leaning",
        sub="the team released the update",
        main="the build server crashed",
        target="The team released the update",
        plan="The team was getting ready to release the update.",
        main_alone="The build server crashed on Friday.",
        confirm="Engineers restored the server, and the update was released.",
        cancel="The server stayed down, and the update was never released.",
    ),
    dict(
        id="b08",
        pragmatic_bias="neutral",
        sub="Marcus returned the library book",
        main="the branch shut down",
        target="Marcus returned the library book",
        plan="Marcus meant to return the library book.",
        main_alone="The branch shut down in March.",
        confirm="Marcus dropped the book at another branch that week.",
        cancel="Marcus never returned the library book.",
    ),
    dict(
        id="b09",
        pragmatic_bias="no_leaning",
        sub="Sofia finished the marathon",
        main="the organisers stopped the race",
        target="Sofia finished the marathon",
        plan="Sofia was hoping to finish the marathon.",
        main_alone="The organisers stopped the race at the four-hour mark.",
        confirm="The remaining runners were allowed to continue, and Sofia finished the marathon.",
        cancel="The course was cleared, and Sofia did not finish the marathon.",
    ),
    dict(
        id="b10",
        pragmatic_bias="no_leaning",
        sub="the journalist published the article",
        main="the editor pulled the story",
        target="The journalist published the article",
        plan="The journalist was about to publish the article.",
        main_alone="The editor pulled the story on Thursday.",
        confirm="The decision was reversed, and the article was published that night.",
        cancel="The decision stood, and the article was never published.",
    ),
    dict(
        id="b11",
        pragmatic_bias="neutral",
        sub="Ken renewed his passport",
        main="the office moved to appointment-only service",
        target="Ken renewed his passport",
        plan="Ken needed to renew his passport.",
        main_alone="The office moved to appointment-only service in January.",
        confirm="Ken booked an appointment and renewed the passport in March.",
        cancel="Ken never got an appointment, and the passport expired unrenewed.",
    ),
    dict(
        id="b12",
        pragmatic_bias="neutral",
        sub="the startup shipped the prototype",
        main="its main supplier went bankrupt",
        target="The startup shipped the prototype",
        plan="The startup was preparing to ship the prototype.",
        main_alone="The startup's main supplier went bankrupt in April.",
        confirm="Another supplier stepped in, and the prototype shipped in June.",
        cancel="No other supplier was found, and the prototype never shipped.",
    ),
    dict(
        id="b13",
        pragmatic_bias="neutral",
        sub="Elena handed in her thesis",
        main="the department changed the submission rules",
        target="Elena handed in her thesis",
        plan="Elena was getting ready to hand in her thesis.",
        main_alone="The department changed the submission rules that term.",
        confirm="Elena reformatted the manuscript and handed in the thesis on Friday.",
        cancel="Elena could not meet the new rules and did not hand in the thesis.",
    ),
    dict(
        id="b14",
        pragmatic_bias="neutral",
        sub="Rosa mailed the package",
        main="the post office ran out of customs forms",
        target="Rosa mailed the package",
        plan="Rosa wanted to mail the package.",
        main_alone="The post office ran out of customs forms.",
        confirm="New forms arrived, and Rosa mailed the package that afternoon.",
        cancel="The forms never arrived, and the package stayed on Rosa's desk.",
    ),
    dict(
        id="b15",
        pragmatic_bias="neutral",
        sub="the committee approved the budget",
        main="two of its members resigned",
        target="The committee approved the budget",
        plan="The committee was expected to approve the budget.",
        main_alone="Two of the committee's members resigned in May.",
        confirm="Replacements were appointed, and the budget was approved.",
        cancel="The vote never took place, and the budget was not approved.",
    ),
    dict(
        id="b16",
        pragmatic_bias="neutral",
        sub="Ahmed sold his car",
        main="the buyer's loan fell through",
        target="Ahmed sold his car",
        plan="Ahmed was trying to sell his car.",
        main_alone="The buyer's loan fell through in October.",
        confirm="Another buyer appeared, and Ahmed sold the car a week later.",
        cancel="No other buyer appeared, and Ahmed kept the car.",
    ),
    dict(
        id="b17",
        pragmatic_bias="no_leaning",
        sub="Nina took the exam",
        main="the testing centre lost power",
        target="Nina took the exam",
        plan="Nina was registered to take the exam.",
        main_alone="The testing centre lost power that morning.",
        confirm="Power returned within the hour, and Nina took the exam.",
        cancel="The session was cancelled, and Nina did not take the exam.",
    ),
    dict(
        id="b18",
        pragmatic_bias="neutral",
        sub="the crew put out the fire",
        main="the water pressure dropped",
        target="The crew put out the fire",
        plan="The crew was working to put out the fire.",
        main_alone="The water pressure dropped shortly past midnight.",
        confirm="Pressure was restored, and the crew put out the fire.",
        cancel="Pressure never returned, and the crew never put out the fire.",
    ),
    dict(
        id="b19",
        pragmatic_bias="neutral",
        sub="Diego deleted the file",
        main="his laptop was confiscated",
        target="Diego deleted the file",
        plan="Diego was going to delete the file.",
        main_alone="Diego's laptop was confiscated on Monday.",
        confirm="The laptop was returned the next day, and Diego deleted the file.",
        cancel="The laptop was never returned, and the file stayed on the disk.",
    ),
    dict(
        id="b20",
        pragmatic_bias="no_leaning",
        sub="the mayor signed the order",
        main="the court issued an injunction",
        target="The mayor signed the order",
        plan="The mayor was preparing to sign the order.",
        main_alone="The court issued an injunction that afternoon.",
        confirm="The injunction was lifted, and the mayor signed the order.",
        cancel="The injunction held, and the order was never signed.",
    ),
    dict(
        id="b21",
        pragmatic_bias="neutral",
        sub="Yuki collected the prize",
        main="the sponsor pulled out",
        target="Yuki collected the prize",
        plan="Yuki was waiting to collect the prize.",
        main_alone="The sponsor pulled out of the competition.",
        confirm="A new sponsor took over, and Yuki collected the prize.",
        cancel="No new sponsor took over, and the prize was never paid out.",
    ),
    dict(
        id="b22",
        pragmatic_bias="no_leaning",
        sub="the students staged the play",
        main="the theatre flooded",
        target="The students staged the play",
        plan="The students were rehearsing to stage the play.",
        main_alone="The theatre flooded the week of the performance.",
        confirm="A hall was found nearby, and the students staged the play.",
        cancel="No other venue was found, and the play was called off.",
    ),
    dict(
        id="b23",
        pragmatic_bias="neutral",
        sub="Carla withdrew the cash",
        main="the cash machine went offline",
        target="Carla withdrew the cash",
        plan="Carla needed to withdraw the cash.",
        main_alone="The cash machine went offline that evening.",
        confirm="The machine came back online, and Carla withdrew the cash.",
        cancel="The machine stayed offline, and Carla went home with nothing.",
    ),
    dict(
        id="b24",
        pragmatic_bias="neutral",
        sub="the surgeon performed the operation",
        main="the patient's fever spiked",
        target="The surgeon performed the operation",
        plan="The surgeon was scheduled to perform the operation.",
        main_alone="The patient's fever spiked overnight.",
        confirm="The fever came down, and the surgeon performed the operation that evening.",
        cancel="The fever persisted, and the operation was never performed.",
    ),
    dict(
        id="b25",
        pragmatic_bias="yes_leaning",
        sub="Tomas repaid the loan",
        main="the lender sold the debt",
        target="Tomas repaid the loan",
        plan="Tomas was arranging to repay the loan.",
        main_alone="The lender sold the debt to a collection agency.",
        confirm="The new holder accepted payment, and Tomas repaid the loan.",
        cancel="The account was frozen in a dispute, and the loan was not repaid.",
    ),
    dict(
        id="b26",
        pragmatic_bias="neutral",
        sub="the village rebuilt the bridge",
        main="the funding was suspended",
        target="The village rebuilt the bridge",
        plan="The village was planning to rebuild the bridge.",
        main_alone="The funding was suspended that spring.",
        confirm="Funding resumed, and the village rebuilt the bridge that summer.",
        cancel="Funding never resumed, and the bridge was left as it was.",
    ),
    dict(
        id="b27",
        pragmatic_bias="no_leaning",
        sub="Hana registered for the course",
        main="the class filled up",
        target="Hana registered for the course",
        plan="Hana wanted to register for the course.",
        main_alone="The class filled up within a day.",
        confirm="A place opened, and Hana registered for the course.",
        cancel="No place opened, and Hana did not register for the course.",
    ),
    dict(
        id="b28",
        pragmatic_bias="yes_leaning",
        sub="the company paid the fine",
        main="the regulator revised the amount",
        target="The company paid the fine",
        plan="The company was expected to pay the fine.",
        main_alone="The regulator revised the amount in June.",
        confirm="The revised amount was settled, and the company paid the fine.",
        cancel="The dispute continued, and the company never paid the fine.",
    ),
    dict(
        id="b29",
        pragmatic_bias="neutral",
        sub="Ivan reached the summit",
        main="a storm moved in",
        target="Ivan reached the summit",
        plan="Ivan was climbing toward the summit.",
        main_alone="A storm moved in during the night.",
        confirm="The weather cleared by dawn, and Ivan reached the summit.",
        cancel="The team turned back, and Ivan did not reach the summit.",
    ),
    dict(
        id="b30",
        pragmatic_bias="no_leaning",
        sub="Grace adopted the dog",
        main="the shelter closed for quarantine",
        target="Grace adopted the dog",
        plan="Grace was hoping to adopt the dog.",
        main_alone="The shelter closed for quarantine in February.",
        confirm="The quarantine ended, and Grace adopted the dog.",
        cancel="The dog was moved to another city, and Grace did not adopt the dog.",
    ),
    dict(
        id="b31",
        pragmatic_bias="no_leaning",
        sub="the engineers fixed the leak",
        main="the tunnel was sealed",
        target="The engineers fixed the leak",
        plan="The engineers were sent to fix the leak.",
        main_alone="The tunnel was sealed for safety.",
        confirm="The tunnel was opened again, and the engineers fixed the leak.",
        cancel="The tunnel stayed sealed, and the leak was never fixed.",
    ),
    dict(
        id="b32",
        pragmatic_bias="neutral",
        sub="Leo apologised to his sister",
        main="she left the country",
        target="Leo apologised to his sister",
        plan="Leo was thinking about apologising to his sister.",
        main_alone="Leo's sister left the country in August.",
        confirm="Leo called her abroad and apologised.",
        cancel="They never spoke again, and Leo never apologised.",
    ),
    dict(
        id="b33",
        pragmatic_bias="no_leaning",
        sub="the auction house sold the painting",
        main="the owner withdrew it",
        target="The auction house sold the painting",
        plan="The auction house was preparing to sell the painting.",
        main_alone="The owner withdrew the painting from the sale.",
        confirm="The painting was relisted and sold in the autumn sale.",
        cancel="The painting was never relisted and was not sold.",
    ),
    dict(
        id="b34",
        pragmatic_bias="neutral",
        sub="Anya finished the report",
        main="her contract ended",
        target="Anya finished the report",
        plan="Anya was working on the report.",
        main_alone="Anya's contract ended in November.",
        confirm="Anya was rehired for a week and finished the report.",
        cancel="The work passed to someone else, and Anya did not finish the report.",
    ),
    dict(
        id="b35",
        pragmatic_bias="neutral",
        sub="the farmer harvested the wheat",
        main="hail flattened part of the field",
        target="The farmer harvested the wheat",
        plan="The farmer was about to harvest the wheat.",
        main_alone="Hail flattened part of the field in July.",
        confirm="The rest of the field was cut, and the farmer harvested the wheat.",
        cancel="The whole crop was lost, and the wheat was never harvested.",
    ),
    dict(
        id="b36",
        pragmatic_bias="no_leaning",
        sub="Peter booked the flight",
        main="the airline suspended the route",
        target="Peter booked the flight",
        plan="Peter was going to book the flight.",
        main_alone="The airline suspended the route in September.",
        confirm="The route reopened, and Peter booked the flight.",
        cancel="The route stayed closed, and Peter did not book the flight.",
    ),
    dict(
        id="b37",
        pragmatic_bias="no_leaning",
        sub="the council demolished the old mill",
        main="preservation status was granted",
        target="The council demolished the old mill",
        plan="The council was planning to demolish the old mill.",
        main_alone="Preservation status was granted that year.",
        confirm="The status was revoked, and the council demolished the old mill.",
        cancel="The status held, and the old mill is still standing.",
    ),
    dict(
        id="b38",
        pragmatic_bias="neutral",
        sub="Mira had her son vaccinated",
        main="the clinic ran out of doses",
        target="Mira had her son vaccinated",
        plan="Mira wanted to have her son vaccinated.",
        main_alone="The clinic ran out of doses that month.",
        confirm="A new shipment arrived, and Mira had her son vaccinated.",
        cancel="No shipment arrived, and Mira's son was not vaccinated.",
    ),
    dict(
        id="b39",
        pragmatic_bias="no_leaning",
        sub="the archivist digitised the manuscript",
        main="the reading room was closed",
        target="The archivist digitised the manuscript",
        plan="The archivist was assigned to digitise the manuscript.",
        main_alone="The reading room was closed for repairs.",
        confirm="The reading room reopened, and the archivist digitised the manuscript.",
        cancel="The reading room stayed closed, and the manuscript was never digitised.",
    ),
    dict(
        id="b40",
        pragmatic_bias="yes_leaning",
        sub="Ravi cancelled the subscription",
        main="the provider changed its billing system",
        target="Ravi cancelled the subscription",
        plan="Ravi meant to cancel the subscription.",
        main_alone="The provider changed its billing system in July.",
        confirm="Ravi reached an agent and cancelled the subscription.",
        cancel="Ravi never reached an agent, and the subscription stayed active.",
    ),
    dict(
        id="b41",
        pragmatic_bias="neutral",
        sub="the technician calibrated the spectrometer",
        main="the power supply failed",
        target="The technician calibrated the spectrometer",
        plan="The technician was due to calibrate the spectrometer.",
        main_alone="The power supply failed at eight in the morning.",
        confirm="A backup generator came on, and the spectrometer was calibrated.",
        cancel="The lab stayed dark all day, and the spectrometer was never calibrated.",
    ),
    dict(
        id="b42",
        pragmatic_bias="no_leaning",
        sub="Dara scored the penalty",
        main="the referee blew the final whistle",
        target="Dara scored the penalty",
        plan="Dara was lining up to take the penalty.",
        main_alone="The referee blew the final whistle in the ninth minute of stoppage time.",
        confirm="The referee allowed the kick to be taken, and Dara scored the penalty.",
        cancel="The whistle stood, and the penalty was never taken.",
    ),
    dict(
        id="b43",
        pragmatic_bias="neutral",
        sub="the witness finished her testimony",
        main="the judge adjourned the session",
        target="The witness finished her testimony",
        plan="The witness was partway through her testimony.",
        main_alone="The judge adjourned the session at four.",
        confirm="The session resumed on Thursday and the witness finished her testimony.",
        cancel="The case collapsed, and the witness never finished her testimony.",
    ),
    dict(
        id="b44",
        pragmatic_bias="no_leaning",
        sub="the paramedics reached the casualty",
        main="a second section of the tunnel collapsed",
        target="The paramedics reached the casualty",
        plan="The paramedics were working their way into the tunnel.",
        main_alone="A second section of the tunnel collapsed at midnight.",
        confirm="A rescue team cut a new shaft, and the paramedics reached the casualty.",
        cancel="The tunnel was declared unsafe, and the paramedics never reached the casualty.",
    ),
    dict(
        id="b45",
        pragmatic_bias="neutral",
        sub="Tobias changed his currency",
        main="the exchange desk shut for the evening",
        target="Tobias changed his currency",
        plan="Tobias needed to change his currency.",
        main_alone="The exchange desk shut for the evening.",
        confirm="A bureau in the arrivals hall was still open, and Tobias changed his currency.",
        cancel="Nothing else was open, and Tobias never changed his currency.",
    ),
    dict(
        id="b46",
        pragmatic_bias="neutral",
        sub="the chef plated the dessert",
        main="the walk-in freezer failed",
        target="The chef plated the dessert",
        plan="The chef was preparing to plate the dessert.",
        main_alone="The walk-in freezer failed during service.",
        confirm="The sorbet was salvaged, and the chef plated the dessert.",
        cancel="The sorbet was ruined, and the dessert was never served.",
    ),
    dict(
        id="b47",
        pragmatic_bias="no_leaning",
        sub="the intern merged the branch",
        main="the repository was archived",
        target="The intern merged the branch",
        plan="The intern was planning to merge the branch.",
        main_alone="The repository was archived in June.",
        confirm="The repository was briefly unarchived, and the intern merged the branch.",
        cancel="The repository stayed archived, and the branch was never merged.",
    ),
    dict(
        id="b48",
        pragmatic_bias="neutral",
        sub="Lucia handed back the marked essays",
        main="term ended",
        target="Lucia handed back the marked essays",
        plan="Lucia still had the marked essays to hand back.",
        main_alone="Term ended on the fifteenth.",
        confirm="Lucia posted them out, and the marked essays were handed back.",
        cancel="The essays sat in her office all summer and were never handed back.",
    ),
    dict(
        id="b49",
        pragmatic_bias="neutral",
        sub="the trader closed the position",
        main="the exchange halted trading",
        target="The trader closed the position",
        plan="The trader was trying to close the position.",
        main_alone="The exchange halted trading for an hour.",
        confirm="Trading resumed, and the trader closed the position.",
        cancel="The halt lasted all session, and the position was never closed.",
    ),
    dict(
        id="b50",
        pragmatic_bias="yes_leaning",
        sub="Nadia told her father the news",
        main="his hearing aid broke",
        target="Nadia told her father the news",
        plan="Nadia had been meaning to tell her father the news.",
        main_alone="Her father's hearing aid broke that week.",
        confirm="She wrote it in a letter, and her father was told the news.",
        cancel="She kept putting it off, and her father was never told.",
    ),
    dict(
        id="b51",
        pragmatic_bias="no_leaning",
        sub="the roofers sealed the skylight",
        main="the storm arrived",
        target="The roofers sealed the skylight",
        plan="The roofers were due to seal the skylight.",
        main_alone="The storm arrived on Sunday night.",
        confirm="There was a lull at dawn, and the roofers sealed the skylight.",
        cancel="The storm did not let up, and the skylight was never sealed.",
    ),
    dict(
        id="b52",
        pragmatic_bias="neutral",
        sub="the photographer filed the picture",
        main="the satellite link dropped",
        target="The photographer filed the picture",
        plan="The photographer was about to file the picture.",
        main_alone="The satellite link dropped at seven.",
        confirm="The link came back, and the photographer filed the picture.",
        cancel="The link stayed down, and the picture was never filed.",
    ),
    dict(
        id="b53",
        pragmatic_bias="neutral",
        sub="the vet treated the last calf",
        main="the road washed out",
        target="The vet treated the last calf",
        plan="The vet still had one calf to treat.",
        main_alone="The road washed out overnight.",
        confirm="The vet came back by tractor, and the last calf was treated.",
        cancel="The farm stayed cut off, and the last calf was never treated.",
    ),
    dict(
        id="b54",
        pragmatic_bias="no_leaning",
        sub="the garrison surrendered the fort",
        main="the relief column arrived",
        target="The garrison surrendered the fort",
        plan="The garrison was preparing to surrender the fort.",
        main_alone="The relief column arrived on the fourth day.",
        confirm="The relief column was driven back, and the garrison surrendered the fort.",
        cancel="The siege was lifted, and the fort was never surrendered.",
    ),
    dict(
        id="b55",
        pragmatic_bias="neutral",
        sub="the quartet played the encore",
        main="the hall lost power",
        target="The quartet played the encore",
        plan="The quartet had an encore prepared.",
        main_alone="The hall lost power during the first half.",
        confirm="The audience lit the stage with their phones, and the quartet played the encore.",
        cancel="The concert was abandoned, and the encore was never played.",
    ),
    dict(
        id="b56",
        pragmatic_bias="neutral",
        sub="Sam refunded the customer",
        main="the till was locked for the audit",
        target="Sam refunded the customer",
        plan="Sam was about to refund the customer.",
        main_alone="The till was locked for the audit.",
        confirm="A manager opened it again, and Sam refunded the customer.",
        cancel="The audit ran all week, and the customer was never refunded.",
    ),
    dict(
        id="b57",
        pragmatic_bias="yes_leaning",
        sub="the driver delivered the last parcel",
        main="the depot closed for the night",
        target="The driver delivered the last parcel",
        plan="The driver had one parcel left to deliver.",
        main_alone="The depot closed for the night at nine.",
        confirm="The driver kept the van out, and the last parcel was delivered.",
        cancel="The route was abandoned, and the last parcel was never delivered.",
    ),
    dict(
        id="b58",
        pragmatic_bias="no_leaning",
        sub="the rangers relocated the nest",
        main="the cliff gave way",
        target="The rangers relocated the nest",
        plan="The rangers were planning to relocate the nest.",
        main_alone="The cliff gave way in the night.",
        confirm="A ledge survived the collapse, and the rangers relocated the nest.",
        cancel="The nest went down with the cliff and was never relocated.",
    ),
    dict(
        id="b59",
        pragmatic_bias="neutral",
        sub="the team lifted the mosaic",
        main="the site flooded",
        target="The team lifted the mosaic",
        plan="The team was preparing to lift the mosaic.",
        main_alone="The site flooded in November.",
        confirm="The water was pumped out, and the team lifted the mosaic.",
        cancel="The trench stayed underwater, and the mosaic was never lifted.",
    ),
    dict(
        id="b60",
        pragmatic_bias="neutral",
        sub="the translator delivered the manuscript",
        main="the publisher went into administration",
        target="The translator delivered the manuscript",
        plan="The translator was finishing the manuscript.",
        main_alone="The publisher went into administration in spring.",
        confirm="Another house bought the rights, and the translator delivered the manuscript.",
        cancel="The contract lapsed, and the manuscript was never delivered.",
    ),
    dict(
        id="b61",
        pragmatic_bias="neutral",
        sub="the mechanic replaced the valve",
        main="the hangar was sealed",
        target="The mechanic replaced the valve",
        plan="The mechanic was scheduled to replace the valve.",
        main_alone="The hangar was sealed for a safety inspection.",
        confirm="The hangar reopened, and the mechanic replaced the valve.",
        cancel="The aircraft was scrapped, and the valve was never replaced.",
    ),
    dict(
        id="b62",
        pragmatic_bias="neutral",
        sub="the student titrated the sample",
        main="the burette cracked",
        target="The student titrated the sample",
        plan="The student was setting up to titrate the sample.",
        main_alone="The burette cracked during setup.",
        confirm="A spare burette was found, and the student titrated the sample.",
        cancel="No spare was available, and the sample was never titrated.",
    ),
    dict(
        id="b63",
        pragmatic_bias="neutral",
        sub="Dr Okafor signed the discharge papers",
        main="the ward went into lockdown",
        target="Dr Okafor signed the discharge papers",
        plan="Dr Okafor was about to sign the discharge papers.",
        main_alone="The ward went into lockdown that afternoon.",
        confirm="The lockdown was lifted, and Dr Okafor signed the discharge papers.",
        cancel="The lockdown held for a fortnight, and the papers were never signed.",
    ),
    dict(
        id="b64",
        pragmatic_bias="neutral",
        sub="Farid collected his residence card",
        main="the office suspended appointments",
        target="Farid collected his residence card",
        plan="Farid was waiting to collect his residence card.",
        main_alone="The office suspended appointments in August.",
        confirm="The card was posted to him, and Farid collected his residence card.",
        cancel="Appointments never resumed, and the card was never collected.",
    ),
    dict(
        id="b65",
        pragmatic_bias="no_leaning",
        sub="the couple exchanged their vows",
        main="the marquee blew down",
        target="The couple exchanged their vows",
        plan="The couple were about to exchange their vows.",
        main_alone="The marquee blew down in the gale.",
        confirm="The ceremony moved into the barn, and the couple exchanged their vows.",
        cancel="The wedding was called off, and the vows were never exchanged.",
    ),
    dict(
        id="b66",
        pragmatic_bias="neutral",
        sub="the crew hauled in the net",
        main="the winch jammed",
        target="The crew hauled in the net",
        plan="The crew were starting to haul in the net.",
        main_alone="The winch jammed in heavy swell.",
        confirm="The winch was freed, and the crew hauled in the net.",
        cancel="The net was cut loose and never hauled in.",
    ),
    dict(
        id="b67",
        pragmatic_bias="neutral",
        sub="the returning officer announced the result",
        main="the count was suspended",
        target="The returning officer announced the result",
        plan="The returning officer was ready to announce the result.",
        main_alone="The count was suspended at three in the morning.",
        confirm="The count resumed, and the returning officer announced the result.",
        cancel="The election was voided, and the result was never announced.",
    ),
    dict(
        id="b68",
        pragmatic_bias="neutral",
        sub="the understudy learned the part",
        main="the production was postponed",
        target="The understudy learned the part",
        plan="The understudy had started learning the part.",
        main_alone="The production was postponed indefinitely.",
        confirm="Rehearsals restarted, and the understudy learned the part.",
        cancel="The production was cancelled, and the part was never learned.",
    ),
    dict(
        id="b69",
        pragmatic_bias="yes_leaning",
        sub="the dentist fitted the crown",
        main="the practice was flooded",
        target="The dentist fitted the crown",
        plan="The dentist was ready to fit the crown.",
        main_alone="The practice was flooded in January.",
        confirm="The practice reopened, and the dentist fitted the crown.",
        cancel="The patient moved away, and the crown was never fitted.",
    ),
    dict(
        id="b70",
        pragmatic_bias="no_leaning",
        sub="the helicopter lifted the climber off the ridge",
        main="the cloud came down",
        target="The helicopter lifted the climber off the ridge",
        plan="The helicopter was approaching the ridge.",
        main_alone="The cloud came down over the summit.",
        confirm="A gap opened, and the helicopter lifted the climber off the ridge.",
        cancel="The cloud never cleared, and the climber was brought down on foot.",
    ),
    dict(
        id="b71",
        pragmatic_bias="neutral",
        sub="the conservator repaired the binding",
        main="the humidity control failed",
        target="The conservator repaired the binding",
        plan="The conservator was due to repair the binding.",
        main_alone="The humidity control failed over the weekend.",
        confirm="The room was stabilised, and the conservator repaired the binding.",
        cancel="The volume was withdrawn, and the binding was never repaired.",
    ),
    dict(
        id="b72",
        pragmatic_bias="no_leaning",
        sub="the founders filed the patent",
        main="a competitor published the design",
        target="The founders filed the patent",
        plan="The founders were preparing to file the patent.",
        main_alone="A competitor published the design in March.",
        confirm="The claims were rewritten, and the founders filed the patent.",
        cancel="The application was abandoned, and the patent was never filed.",
    ),
    dict(
        id="b73",
        pragmatic_bias="neutral",
        sub="the volunteers distributed the last blankets",
        main="the bridge was closed",
        target="The volunteers distributed the last blankets",
        plan="The volunteers still had blankets to distribute.",
        main_alone="The bridge was closed because of the landslide.",
        confirm="A boat took them across, and the last blankets were distributed.",
        cancel="The valley stayed cut off, and the last blankets were never distributed.",
    ),
    dict(
        id="b74",
        pragmatic_bias="no_leaning",
        sub="the observatory recorded the transit",
        main="cloud rolled in",
        target="The observatory recorded the transit",
        plan="The observatory was set up to record the transit.",
        main_alone="Cloud rolled in from the west.",
        confirm="The sky cleared in time, and the observatory recorded the transit.",
        cancel="The cloud held, and the transit was never recorded.",
    ),
    dict(
        id="b75",
        pragmatic_bias="neutral",
        sub="Bea planted the bulbs",
        main="the ground froze",
        target="Bea planted the bulbs",
        plan="Bea meant to plant the bulbs.",
        main_alone="The ground froze in early November.",
        confirm="There was a thaw, and Bea planted the bulbs.",
        cancel="The bulbs dried out in the shed and were never planted.",
    ),
    dict(
        id="b76",
        pragmatic_bias="neutral",
        sub="the admin rotated the keys",
        main="the server was seized",
        target="The admin rotated the keys",
        plan="The admin was about to rotate the keys.",
        main_alone="The server was seized as evidence.",
        confirm="A replacement host was built, and the admin rotated the keys.",
        cancel="The service was shut down, and the keys were never rotated.",
    ),
    dict(
        id="b77",
        pragmatic_bias="no_leaning",
        sub="Kofi qualified for the final",
        main="the meet was abandoned",
        target="Kofi qualified for the final",
        plan="Kofi was hoping to qualify for the final.",
        main_alone="The meet was abandoned because of the storm.",
        confirm="The heats were rerun a week later, and Kofi qualified for the final.",
        cancel="The meet was written off, and Kofi did not qualify for the final.",
    ),
    dict(
        id="b78",
        pragmatic_bias="neutral",
        sub="the port cleared the container",
        main="the strike began",
        target="The port cleared the container",
        plan="The port was due to clear the container.",
        main_alone="The strike began on Monday.",
        confirm="A skeleton crew worked the berth, and the port cleared the container.",
        cancel="The strike ran for six weeks, and the container was never cleared.",
    ),
    dict(
        id="b79",
        pragmatic_bias="neutral",
        sub="the crew shot the final scene",
        main="the lead actor fell ill",
        target="The crew shot the final scene",
        plan="The crew had the final scene left to shoot.",
        main_alone="The lead actor fell ill in the last week.",
        confirm="The actor recovered, and the crew shot the final scene.",
        cancel="The shoot was abandoned, and the final scene was never shot.",
    ),
    dict(
        id="b80",
        pragmatic_bias="neutral",
        sub="the clinic finished the second round",
        main="the cold chain broke",
        target="The clinic finished the second round",
        plan="The clinic was partway through the second round.",
        main_alone="The cold chain broke during the heatwave.",
        confirm="A fresh consignment arrived, and the clinic finished the second round.",
        cancel="No replacement doses came, and the second round was never finished.",
    ),
    dict(
        id="b41",
        pragmatic_bias="neutral",
        sub="Claire filed the appeal",
        main="the registry moved to electronic submissions only",
        target="Claire filed the appeal",
        plan="Claire was preparing to file the appeal.",
        main_alone="The registry moved to electronic submissions only that month.",
        confirm="Claire re-filed the appeal online the same week.",
        cancel="Claire never managed to file the appeal.",
    ),
    dict(
        id="b42",
        pragmatic_bias="no_leaning",
        sub="the ward transferred the patient",
        main="the ambulance bay flooded",
        target="The ward transferred the patient",
        plan="The ward was due to transfer the patient.",
        main_alone="The ambulance bay flooded overnight.",
        confirm="A side entrance was opened and the patient was transferred.",
        cancel="The transfer was cancelled and the patient stayed on the ward.",
    ),
    dict(
        id="b43",
        pragmatic_bias="no_leaning",
        sub="Jonas cashed the cheque",
        main="the account was closed",
        target="Jonas cashed the cheque",
        plan="Jonas meant to cash the cheque.",
        main_alone="The account was closed in April.",
        confirm="The bank honoured it anyway and Jonas cashed the cheque.",
        cancel="The cheque was refused and Jonas never cashed it.",
    ),
    dict(
        id="b44",
        pragmatic_bias="neutral",
        sub="the choir recorded the album",
        main="the studio lost its lease",
        target="The choir recorded the album",
        plan="The choir was booked to record the album.",
        main_alone="The studio lost its lease that spring.",
        confirm="Another studio took the booking and the album was recorded.",
        cancel="No studio was found and the album was never recorded.",
    ),
    dict(
        id="b45",
        pragmatic_bias="neutral",
        sub="Beatriz defended her dissertation",
        main="the external examiner withdrew",
        target="Beatriz defended her dissertation",
        plan="Beatriz was scheduled to defend her dissertation.",
        main_alone="The external examiner withdrew in June.",
        confirm="A replacement was found and Beatriz defended the dissertation.",
        cancel="No replacement was found and the defence never took place.",
    ),
    dict(
        id="b46",
        pragmatic_bias="no_leaning",
        sub="the driver delivered the parcel",
        main="the road was closed by police",
        target="The driver delivered the parcel",
        plan="The driver set out with the parcel.",
        main_alone="The road was closed by police that morning.",
        confirm="A detour opened and the parcel was delivered.",
        cancel="The parcel was returned to the depot undelivered.",
    ),
    dict(
        id="b47",
        pragmatic_bias="neutral",
        sub="Imran renewed the lease",
        main="the landlord put the building up for sale",
        target="Imran renewed the lease",
        plan="Imran intended to renew the lease.",
        main_alone="The landlord put the building up for sale in May.",
        confirm="The sale fell through and Imran renewed the lease.",
        cancel="The building was sold and the lease was not renewed.",
    ),
    dict(
        id="b48",
        pragmatic_bias="no_leaning",
        sub="the museum acquired the sculpture",
        main="its acquisitions budget was frozen",
        target="The museum acquired the sculpture",
        plan="The museum hoped to acquire the sculpture.",
        main_alone="The museum's acquisitions budget was frozen that year.",
        confirm="A donor covered the cost and the sculpture was acquired.",
        cancel="The freeze held and the sculpture went elsewhere.",
    ),
    dict(
        id="b49",
        pragmatic_bias="neutral",
        sub="Noor submitted the tax return",
        main="the accounting software stopped working",
        target="Noor submitted the tax return",
        plan="Noor was about to do the tax return.",
        main_alone="The accounting software stopped working in January.",
        confirm="Noor filed on paper and the return was submitted.",
        cancel="The deadline passed and the return was never submitted.",
    ),
    dict(
        id="b50",
        pragmatic_bias="no_leaning",
        sub="the guide led the group to the cave",
        main="the tide came in",
        target="The guide led the group to the cave",
        plan="The guide planned to lead the group to the cave.",
        main_alone="The tide came in early that afternoon.",
        confirm="The group went round by the cliff path and reached the cave.",
        cancel="The route was impassable and the group never reached the cave.",
    ),
    dict(
        id="b51",
        pragmatic_bias="yes_leaning",
        sub="Theo returned the rental car",
        main="the depot changed its opening hours",
        target="Theo returned the rental car",
        plan="Theo needed to return the rental car.",
        main_alone="The depot changed its opening hours in August.",
        confirm="Theo used the key drop and returned the car that night.",
        cancel="Theo kept the car for another week.",
    ),
    dict(
        id="b52",
        pragmatic_bias="neutral",
        sub="the union called the strike",
        main="the employer made a new offer",
        target="The union called the strike",
        plan="The union was preparing to call a strike.",
        main_alone="The employer made a new offer on Monday.",
        confirm="The offer was rejected and the union called the strike.",
        cancel="The offer was accepted and no strike was called.",
    ),
    dict(
        id="b53",
        pragmatic_bias="neutral",
        sub="Ingrid published the dataset",
        main="the ethics board raised an objection",
        target="Ingrid published the dataset",
        plan="Ingrid was ready to publish the dataset.",
        main_alone="The ethics board raised an objection in March.",
        confirm="The objection was resolved and the dataset was published.",
        cancel="The objection stood and the dataset was never published.",
    ),
    dict(
        id="b54",
        pragmatic_bias="no_leaning",
        sub="the bakery opened for the morning",
        main="a water main burst on the street",
        target="The bakery opened for the morning",
        plan="The bakery was due to open for the morning.",
        main_alone="A water main burst on the street at dawn.",
        confirm="The supply was restored and the bakery opened.",
        cancel="The street stayed closed and the bakery did not open.",
    ),
    dict(
        id="b55",
        pragmatic_bias="neutral",
        sub="Samuel proposed to Ada",
        main="her flight was brought forward",
        target="Samuel proposed to Ada",
        plan="Samuel was planning to propose to Ada.",
        main_alone="Ada's flight was brought forward by a day.",
        confirm="Samuel drove to the airport and proposed there.",
        cancel="They missed each other and Samuel did not propose.",
    ),
    dict(
        id="b56",
        pragmatic_bias="neutral",
        sub="the referee restarted the match",
        main="floodlight failure stopped play",
        target="The referee restarted the match",
        plan="The referee was about to restart the match.",
        main_alone="Floodlight failure stopped play in the second half.",
        confirm="The lights came back and the referee restarted the match.",
        cancel="The lights stayed off and the match was abandoned.",
    ),
    dict(
        id="b57",
        pragmatic_bias="no_leaning",
        sub="Wei backed up the server",
        main="the data centre lost power",
        target="Wei backed up the server",
        plan="Wei was scheduled to back up the server.",
        main_alone="The data centre lost power that night.",
        confirm="Power returned and Wei completed the backup.",
        cancel="Nothing was recovered and the backup was never made.",
    ),
    dict(
        id="b58",
        pragmatic_bias="neutral",
        sub="the charity distributed the food parcels",
        main="the warehouse was condemned",
        target="The charity distributed the food parcels",
        plan="The charity had food parcels ready to distribute.",
        main_alone="The warehouse was condemned in October.",
        confirm="The stock was moved and the parcels were distributed.",
        cancel="The stock was destroyed and no parcels were distributed.",
    ),
    dict(
        id="b59",
        pragmatic_bias="neutral",
        sub="Hugo sat down to dinner with his father",
        main="the pager went off",
        target="Hugo sat down to dinner with his father",
        plan="Hugo was going to have dinner with his father.",
        main_alone="The pager went off just after seven.",
        confirm="The call was handled quickly and they had dinner together.",
        cancel="Hugo left for the hospital and they never had dinner.",
    ),
    dict(
        id="b60",
        pragmatic_bias="no_leaning",
        sub="the crew launched the lifeboat",
        main="the winch jammed",
        target="The crew launched the lifeboat",
        plan="The crew were preparing to launch the lifeboat.",
        main_alone="The winch jammed in heavy swell.",
        confirm="The winch was freed and the lifeboat was launched.",
        cancel="The winch could not be freed and the lifeboat stayed aboard.",
    ),
    dict(
        id="b61",
        pragmatic_bias="neutral",
        sub="Tanya translated the contract",
        main="the client changed agencies",
        target="Tanya translated the contract",
        plan="Tanya was asked to translate the contract.",
        main_alone="The client changed agencies in February.",
        confirm="The new agency kept Tanya on and the contract was translated.",
        cancel="The work was withdrawn and Tanya did not translate it.",
    ),
    dict(
        id="b62",
        pragmatic_bias="no_leaning",
        sub="the school reopened the pool",
        main="an inspection found cracked tiles",
        target="The school reopened the pool",
        plan="The school intended to reopen the pool.",
        main_alone="An inspection found cracked tiles that term.",
        confirm="The tiles were replaced and the pool reopened.",
        cancel="The repairs were never funded and the pool stayed shut.",
    ),
    dict(
        id="b63",
        pragmatic_bias="neutral",
        sub="Jae-won signed the recording deal",
        main="the label was bought out",
        target="Jae-won signed the recording deal",
        plan="Jae-won was negotiating a recording deal.",
        main_alone="The label was bought out in July.",
        confirm="The new owners honoured the terms and Jae-won signed.",
        cancel="The deal lapsed and Jae-won did not sign.",
    ),
    dict(
        id="b64",
        pragmatic_bias="neutral",
        sub="the pharmacist dispensed the medication",
        main="the prescription system went down",
        target="The pharmacist dispensed the medication",
        plan="The pharmacist was about to dispense the medication.",
        main_alone="The prescription system went down that afternoon.",
        confirm="The system came back and the medication was dispensed.",
        cancel="The patient was sent away without the medication.",
    ),
    dict(
        id="b65",
        pragmatic_bias="yes_leaning",
        sub="Marta boarded up the shopfront",
        main="the storm changed course",
        target="Marta boarded up the shopfront",
        plan="Marta was getting ready to board up the shopfront.",
        main_alone="The storm changed course overnight.",
        confirm="Marta boarded up the shopfront anyway.",
        cancel="No boarding was needed and Marta left the shopfront open.",
    ),
    dict(
        id="b66",
        pragmatic_bias="no_leaning",
        sub="the foundation awarded the grant",
        main="the applicant withdrew the proposal",
        target="The foundation awarded the grant",
        plan="The foundation was minded to award the grant.",
        main_alone="The applicant withdrew the proposal in September.",
        confirm="The proposal was resubmitted and the grant was awarded.",
        cancel="The proposal was never resubmitted and no grant was awarded.",
    ),
    dict(
        id="b67",
        pragmatic_bias="no_leaning",
        sub="Felix reached the checkpoint",
        main="the pass was closed by snow",
        target="Felix reached the checkpoint",
        plan="Felix was heading for the checkpoint.",
        main_alone="The pass was closed by snow that week.",
        confirm="The pass reopened and Felix reached the checkpoint.",
        cancel="Felix turned back and never reached the checkpoint.",
    ),
    dict(
        id="b68",
        pragmatic_bias="neutral",
        sub="the editor sent the manuscript to print",
        main="a libel concern was raised",
        target="The editor sent the manuscript to print",
        plan="The editor was ready to send the manuscript to print.",
        main_alone="A libel concern was raised in November.",
        confirm="The passage was cut and the manuscript went to print.",
        cancel="The concern stood and the manuscript was never printed.",
    ),
    dict(
        id="b69",
        pragmatic_bias="no_leaning",
        sub="Adaeze transferred the deposit",
        main="the payment window closed",
        target="Adaeze transferred the deposit",
        plan="Adaeze was going to transfer the deposit.",
        main_alone="The payment window closed at five.",
        confirm="The window was extended and Adaeze transferred the deposit.",
        cancel="The window stayed shut and the deposit was never transferred.",
    ),
    dict(
        id="b70",
        pragmatic_bias="no_leaning",
        sub="the laboratory sequenced the sample",
        main="the freezer failed",
        target="The laboratory sequenced the sample",
        plan="The laboratory had the sample ready to sequence.",
        main_alone="The freezer failed over the weekend.",
        confirm="A backup aliquot survived and the sample was sequenced.",
        cancel="The sample was lost and was never sequenced.",
    ),
    dict(
        id="b71",
        pragmatic_bias="neutral",
        sub="Caleb apologised to the neighbours",
        main="they put the house on the market",
        target="Caleb apologised to the neighbours",
        plan="Caleb thought about apologising to the neighbours.",
        main_alone="The neighbours put the house on the market in spring.",
        confirm="Caleb caught them on moving day and apologised.",
        cancel="The neighbours left and Caleb never apologised.",
    ),
    dict(
        id="b72",
        pragmatic_bias="neutral",
        sub="the council granted the licence",
        main="a petition was lodged against it",
        target="The council granted the licence",
        plan="The council was expected to grant the licence.",
        main_alone="A petition was lodged against the application.",
        confirm="The petition was dismissed and the licence was granted.",
        cancel="The petition succeeded and the licence was refused.",
    ),
    dict(
        id="b73",
        pragmatic_bias="no_leaning",
        sub="Suki fixed the roof",
        main="the scaffolding was taken away",
        target="Suki fixed the roof",
        plan="Suki was going to fix the roof.",
        main_alone="The scaffolding was taken away on Friday.",
        confirm="New scaffolding was hired and Suki fixed the roof.",
        cancel="The roof was left unrepaired through the winter.",
    ),
    dict(
        id="b74",
        pragmatic_bias="no_leaning",
        sub="the ferry company refunded the passengers",
        main="it entered administration",
        target="The ferry company refunded the passengers",
        plan="The ferry company had promised refunds.",
        main_alone="The ferry company entered administration in June.",
        confirm="A rescue deal was agreed and the refunds were paid.",
        cancel="The refunds were never paid.",
    ),
    dict(
        id="b75",
        pragmatic_bias="neutral",
        sub="Dario returned to the stage",
        main="his voice gave out",
        target="Dario returned to the stage",
        plan="Dario was due back on stage.",
        main_alone="Dario's voice gave out during the interval.",
        confirm="His voice recovered and Dario returned to the stage.",
        cancel="The rest of the concert was cancelled.",
    ),
    dict(
        id="b76",
        pragmatic_bias="neutral",
        sub="the surveyor completed the report",
        main="access to the site was refused",
        target="The surveyor completed the report",
        plan="The surveyor was working on the report.",
        main_alone="Access to the site was refused in August.",
        confirm="Access was granted later and the report was completed.",
        cancel="The report was abandoned unfinished.",
    ),
    dict(
        id="b77",
        pragmatic_bias="yes_leaning",
        sub="Amira collected her results",
        main="the results server was taken offline",
        target="Amira collected her results",
        plan="Amira was waiting to collect her results.",
        main_alone="The results server was taken offline for maintenance.",
        confirm="The server came back and Amira collected her results.",
        cancel="The results were never released.",
    ),
    dict(
        id="b78",
        pragmatic_bias="no_leaning",
        sub="the brewery bottled the batch",
        main="contamination was detected in the tank",
        target="The brewery bottled the batch",
        plan="The brewery was ready to bottle the batch.",
        main_alone="Contamination was detected in the tank that week.",
        confirm="The tank was cleared and the batch was bottled.",
        cancel="The batch was poured away unbottled.",
    ),
    dict(
        id="b79",
        pragmatic_bias="neutral",
        sub="Lukas handed over the keys",
        main="the sale was delayed by the solicitors",
        target="Lukas handed over the keys",
        plan="Lukas was ready to hand over the keys.",
        main_alone="The sale was delayed by the solicitors in October.",
        confirm="The delay was resolved and Lukas handed over the keys.",
        cancel="The sale collapsed and the keys were never handed over.",
    ),
    dict(
        id="b80",
        pragmatic_bias="no_leaning",
        sub="the observatory photographed the comet",
        main="cloud cover moved in",
        target="The observatory photographed the comet",
        plan="The observatory planned to photograph the comet.",
        main_alone="Cloud cover moved in that evening.",
        confirm="The sky cleared and the comet was photographed.",
        cancel="The comet passed unphotographed.",
    ),
    dict(
        id="b81",
        pragmatic_bias="neutral",
        sub="Renata paid the contractors",
        main="the invoice was disputed",
        target="Renata paid the contractors",
        plan="Renata was due to pay the contractors.",
        main_alone="The invoice was disputed in March.",
        confirm="The dispute was settled and Renata paid the contractors.",
        cancel="The dispute dragged on and the contractors went unpaid.",
    ),
    dict(
        id="b82",
        pragmatic_bias="no_leaning",
        sub="the team cleared the minefield",
        main="the ceasefire broke down",
        target="The team cleared the minefield",
        plan="The team was assigned to clear the minefield.",
        main_alone="The ceasefire broke down in April.",
        confirm="A new truce held and the minefield was cleared.",
        cancel="The work was abandoned and the minefield was left.",
    ),
    dict(
        id="b83",
        pragmatic_bias="neutral",
        sub="Pablo enrolled his daughter at the school",
        main="the catchment rules changed",
        target="Pablo enrolled his daughter at the school",
        plan="Pablo wanted to enrol his daughter at the school.",
        main_alone="The catchment rules changed that year.",
        confirm="An exception was granted and Pablo enrolled his daughter.",
        cancel="The application was refused and she went elsewhere.",
    ),
    dict(
        id="b84",
        pragmatic_bias="neutral",
        sub="the airline compensated the passengers",
        main="the regulator opened an inquiry",
        target="The airline compensated the passengers",
        plan="The airline was expected to compensate the passengers.",
        main_alone="The regulator opened an inquiry in December.",
        confirm="The inquiry closed and the passengers were compensated.",
        cancel="No compensation was ever paid.",
    ),
    dict(
        id="b85",
        pragmatic_bias="no_leaning",
        sub="Zara replanted the orchard",
        main="the drought order came into force",
        target="Zara replanted the orchard",
        plan="Zara was planning to replant the orchard.",
        main_alone="The drought order came into force in June.",
        confirm="The order was lifted and Zara replanted the orchard.",
        cancel="The ground stayed bare.",
    ),
    dict(
        id="b86",
        pragmatic_bias="no_leaning",
        sub="the historian consulted the archive",
        main="the collection was sealed for conservation",
        target="The historian consulted the archive",
        plan="The historian had arranged to consult the archive.",
        main_alone="The collection was sealed for conservation that autumn.",
        confirm="The seal was lifted and the historian consulted the archive.",
        cancel="The collection stayed sealed and was never consulted.",
    ),
    dict(
        id="b87",
        pragmatic_bias="neutral",
        sub="Otto repaired the church clock",
        main="the tower was declared unsafe",
        target="Otto repaired the church clock",
        plan="Otto was engaged to repair the church clock.",
        main_alone="The tower was declared unsafe in February.",
        confirm="The tower was made safe and Otto repaired the clock.",
        cancel="The clock has not run since.",
    ),
    dict(
        id="b88",
        pragmatic_bias="no_leaning",
        sub="the clinic vaccinated the herd",
        main="movement restrictions were imposed",
        target="The clinic vaccinated the herd",
        plan="The clinic was booked to vaccinate the herd.",
        main_alone="Movement restrictions were imposed that month.",
        confirm="The restrictions were lifted and the herd was vaccinated.",
        cancel="The herd was never vaccinated.",
    ),
    dict(
        id="b89",
        pragmatic_bias="no_leaning",
        sub="Blessing wired the money home",
        main="the transfer service suspended her account",
        target="Blessing wired the money home",
        plan="Blessing was about to wire the money home.",
        main_alone="The transfer service suspended Blessing's account.",
        confirm="The account was restored and the money was wired home.",
        cancel="The money never reached home.",
    ),
    dict(
        id="b90",
        pragmatic_bias="neutral",
        sub="the firm settled the claim",
        main="new evidence surfaced",
        target="The firm settled the claim",
        plan="The firm was ready to settle the claim.",
        main_alone="New evidence surfaced in May.",
        confirm="The evidence was dismissed and the firm settled the claim.",
        cancel="The case went to trial instead.",
    ),
    dict(
        id="b91",
        pragmatic_bias="no_leaning",
        sub="Rafael finished the mural",
        main="the wall was scheduled for demolition",
        target="Rafael finished the mural",
        plan="Rafael was working on the mural.",
        main_alone="The wall was scheduled for demolition that summer.",
        confirm="The demolition was postponed and Rafael finished the mural.",
        cancel="The wall came down with the mural unfinished.",
    ),
    dict(
        id="b92",
        pragmatic_bias="neutral",
        sub="the port released the shipment",
        main="a customs hold was placed on it",
        target="The port released the shipment",
        plan="The port was due to release the shipment.",
        main_alone="A customs hold was placed on the shipment.",
        confirm="The hold was lifted and the shipment was released.",
        cancel="The shipment was seized and never released.",
    ),
    dict(
        id="b93",
        pragmatic_bias="no_leaning",
        sub="Elin skied the descent",
        main="the avalanche risk was raised to high",
        target="Elin skied the descent",
        plan="Elin was hoping to ski the descent.",
        main_alone="The avalanche risk was raised to high that morning.",
        confirm="The risk dropped and Elin skied the descent.",
        cancel="The route was closed and Elin did not ski it.",
    ),
    dict(
        id="b94",
        pragmatic_bias="neutral",
        sub="the press printed the correction",
        main="the proprietor intervened",
        target="The press printed the correction",
        plan="The press was preparing to print a correction.",
        main_alone="The proprietor intervened on Thursday.",
        confirm="The intervention failed and the correction was printed.",
        cancel="No correction ever appeared.",
    ),
    dict(
        id="b95",
        pragmatic_bias="no_leaning",
        sub="Ivo returned the borrowed violin",
        main="the case was left on a train",
        target="Ivo returned the borrowed violin",
        plan="Ivo meant to return the borrowed violin.",
        main_alone="The case was left on a train in September.",
        confirm="The violin was recovered and Ivo returned it.",
        cancel="The violin was never recovered.",
    ),
    dict(
        id="b96",
        pragmatic_bias="neutral",
        sub="the ministry published the figures",
        main="a court order blocked release",
        target="The ministry published the figures",
        plan="The ministry was due to publish the figures.",
        main_alone="A court order blocked release that week.",
        confirm="The order was overturned and the figures were published.",
        cancel="The figures have still not been published.",
    ),
    dict(
        id="b97",
        pragmatic_bias="neutral",
        sub="Siobhan qualified as a pilot",
        main="the flight school closed",
        target="Siobhan qualified as a pilot",
        plan="Siobhan was close to qualifying as a pilot.",
        main_alone="The flight school closed in January.",
        confirm="Another school took her hours and Siobhan qualified.",
        cancel="Siobhan never qualified.",
    ),
    dict(
        id="b98",
        pragmatic_bias="no_leaning",
        sub="the volunteers cleared the beach",
        main="a chemical warning was issued",
        target="The volunteers cleared the beach",
        plan="The volunteers had arranged to clear the beach.",
        main_alone="A chemical warning was issued that weekend.",
        confirm="The warning was withdrawn and the volunteers cleared the beach.",
        cancel="The beach was left as it was.",
    ),
    dict(
        id="b99",
        pragmatic_bias="yes_leaning",
        sub="Konrad testified at the hearing",
        main="the hearing was moved to a closed session",
        target="Konrad testified at the hearing",
        plan="Konrad was called to testify at the hearing.",
        main_alone="The hearing was moved to a closed session.",
        confirm="Konrad was admitted and testified.",
        cancel="Konrad was never called.",
    ),
    dict(
        id="b100",
        pragmatic_bias="neutral",
        sub="the developer released the patch",
        main="the signing certificate expired",
        target="The developer released the patch",
        plan="The developer had the patch ready.",
        main_alone="The signing certificate expired that day.",
        confirm="A new certificate was issued and the patch was released.",
        cancel="The patch was never released.",
    ),
]
