"""E12 — build the corrupted-reference trajectories Z~(0).

A two-arm clamp confounds "untreated" with "correct": the reference prefix Z(0) is the
full model's own correct trajectory.  Z~(0) is untreated but NOT correct, so that

    Y(R) - Y(R~)   is the part of the mediation explained by prefix CONTENT
    Y(R~) - Y(F)   is the residual attributable to the context having been produced
                   under the same perturbation, beyond its surface error content

Z~(0) is generated by the FULL-PRECISION model at temperature tau, so no treatment
touches it.  tau is calibrated so that the task-level error rate of the clamped span
matches that of the treated model's own prefix Z(T) to within `--tol`.

MATCHING STATISTIC -- revised 2026-09-14 after the first criterion failed on contact.

The preregistered criterion was the task-level error rate of the span: a calculator
annotation `<<a op b=c>>` whose stated result is wrong.  Measured against the readout
truncated model it returns **0.000**, not because that model's arithmetic is right but
because it emits no calculator annotations at all: 1 of 500 treated outputs contains
`<<`, against 369 of 500 references.  The treated prefix does not differ from the
reference by being wrong; it differs by being a different kind of text.

That is itself informative -- it is the off-manifold condition that would produce a
non-zero residual -- but it makes an error-RATE match inapplicable.  The statistic is
therefore **divergence from the reference prefix**, which is defined for degenerate
text: mean positional token agreement with Z(0) over the clamped span, with normalized
character edit distance reported alongside as a robustness check.  tau is chosen so
that full-model samples diverge from Z(0) as much as Z(T) does.

If no temperature on the grid reaches the target, that is reported rather than
patched: it would mean the treated prefix cannot be mimicked by an untreated model at
any temperature, the residual is not estimable by this route, and Stage 2 (state
refresh) becomes the only way to separate content from provenance.

Calibration uses a held-out item split; the evaluation split is never used to pick tau.
"""
from __future__ import annotations
import argparse, json, pathlib, re, sys, time
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

import importlib.util
ROOT = pathlib.Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("run_eval", ROOT / "scripts" / "run_eval.py")
run_eval = importlib.util.module_from_spec(spec); spec.loader.exec_module(run_eval)
cspec = importlib.util.spec_from_file_location("clamp", ROOT / "scripts" / "run_e12_clamp.py")
clamp = importlib.util.module_from_spec(cspec); cspec.loader.exec_module(clamp)

CALC = re.compile(r"<<\s*([-\d\.\+\*/\(\) ,]+?)\s*=\s*(-?[\d\.,]+)\s*>>")


def span_has_error(text: str) -> bool:
    """True if any calculator annotation in the span states a wrong result."""
    for expr, stated in CALC.findall(text):
        try:
            got = eval(expr.replace(",", ""), {"__builtins__": {}}, {})
            if abs(float(got) - float(stated.replace(",", ""))) > 1e-6:
                return True
        except Exception:
            return True
    return False


def token_agreement(a_ids, b_ids) -> float:
    """positional token agreement over the overlapping span"""
    n = min(len(a_ids), len(b_ids))
    if n == 0:
        return 1.0
    return sum(1 for i in range(n) if a_ids[i] == b_ids[i]) / n


def char_edit(a: str, b: str) -> float:
    """normalized Levenshtein distance, for the robustness column"""
    if not a and not b:
        return 0.0
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (ca != cb)))
        prev = cur
    return prev[-1] / max(len(a), len(b), 1)


def divergence(pairs) -> tuple:
    """(1 - mean token agreement, mean normalized char edit) against the reference"""
    if not pairs:
        return 1.0, 1.0
    ag = [token_agreement(x, y) for x, y, _, _ in pairs]
    ed = [char_edit(s, t) for _, _, s, t in pairs]
    return 1 - sum(ag) / len(ag), sum(ed) / len(ed)


def error_rate(texts) -> float:
    t = [x for x in texts if x]
    return sum(span_has_error(x) for x in t) / max(len(t), 1)


@torch.no_grad()
def sample(model, tok, items, max_new, stops, bs, temperature, seed):
    torch.manual_seed(seed)
    pad = tok.pad_token_id or tok.eos_token_id
    out = {}
    order = sorted(range(len(items)), key=lambda i: -len(items[i]["prompt"]))
    for s in range(0, len(order), bs):
        idxs = order[s:s + bs]
        enc = tok([items[i]["prompt"] for i in idxs], return_tensors="pt",
                  padding=True, padding_side="left").to(model.device)
        g = model.generate(**enc, max_new_tokens=max_new, do_sample=True,
                           temperature=temperature, top_p=1.0, top_k=0,
                           pad_token_id=pad)
        new = g[:, enc["input_ids"].shape[1]:]
        for j, i in enumerate(idxs):
            txt = tok.decode(new[j], skip_special_tokens=True)
            for st in stops:
                if st in txt:
                    txt = txt.split(st)[0]
            out[i] = {"id": items[i]["id"], "output": txt,
                      "n_new_tokens": int(new[j].shape[0]),
                      "gold": items[i]["gold"], "meta": items[i]["meta"]}
    return [out[i] for i in range(len(items))]


def span_pairs(path, k_frac, refs, tok):
    """(treated ids, reference ids, treated text, reference text) over the clamped span"""
    out = []
    for line in open(path):
        r = json.loads(line)
        if r.get("_meta"):
            continue
        ref = refs.get(r["id"])
        if not ref or ref["L0"] is None:
            continue
        k = int(round(k_frac * ref["L0"]))
        if k == 0:
            continue
        t_ids = tok(r.get("output", "") or "", add_special_tokens=False)["input_ids"][:k]
        r_ids = ref["ids"][:k]
        out.append((t_ids, r_ids,
                    tok.decode(t_ids, skip_special_tokens=True),
                    tok.decode(r_ids, skip_special_tokens=True)))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--tag", required=True)
    ap.add_argument("--cell", default="gsm8k_gen_cot")
    ap.add_argument("--treated-run", required=True,
                    help="the free-running treated run whose error rate is the target")
    ap.add_argument("--frac", type=float, default=0.5)
    ap.add_argument("--n", type=int, default=500)
    ap.add_argument("--calib-n", type=int, default=120, help="held-out split for tau")
    ap.add_argument("--bs", type=int, default=8)
    ap.add_argument("--tol", type=float, default=0.05)
    ap.add_argument("--grid", default="0.7,1.0,1.3,1.6,2.0,2.5,3.0")
    a = ap.parse_args()

    tok = AutoTokenizer.from_pretrained(a.model)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    model = AutoModelForCausalLM.from_pretrained(
        a.model, dtype=torch.bfloat16, device_map="cuda:0").eval()

    full_run = ROOT / "results" / "e01" / a.tag / f"{a.cell}__full.jsonl"
    refs = clamp.reference_table(tok, full_run, a.cell)
    pairs = span_pairs(a.treated_run, a.frac, refs, tok)
    target, target_ed = divergence(pairs)
    n_calc_t = sum("<<" in s for _, _, s, _ in pairs)
    n_calc_r = sum("<<" in s for _, _, _, s in pairs)
    print(f"target divergence of the treated prefix (frac={a.frac:g}) over {len(pairs)} items:\n"
          f"  1 - token agreement vs reference = {target:.3f}\n"
          f"  normalized char edit distance    = {target_ed:.3f}\n"
          f"  calculator annotations present   = {n_calc_t}/{len(pairs)} treated "
          f"vs {n_calc_r}/{len(pairs)} reference "
          f"(why the preregistered error-RATE criterion is inapplicable)", flush=True)

    # calibration split: items beyond the evaluation split, so tau is never fit on
    # the items the contrast is estimated on
    all_items = run_eval.load_items(a.cell, a.n + a.calib_n, 1234)
    calib = all_items[a.n:]
    max_new, stops = run_eval.CELL_GEN[a.cell]

    # the calibration reference is the full model's own greedy trajectory on the
    # calibration items, generated once at temperature 0
    ref_calib = {r["id"]: tok(r["output"], add_special_tokens=False)["input_ids"]
                 for r in sample(model, tok, calib, max_new, stops, a.bs, 1e-6, 1234)}
    best, chosen = None, None
    for tau in [float(x) for x in a.grid.split(",")]:
        recs = sample(model, tok, calib, max_new, stops, a.bs, tau, seed=1234)
        ps = []
        for r in recs:
            rr = ref_calib.get(r["id"])
            if not rr:
                continue
            L0 = clamp.answer_char_pos(a.cell, r["output"])
            kk = len(rr) if L0 is None else max(
                1, int(round(a.frac * len(tok(r["output"][:L0],
                                             add_special_tokens=False)["input_ids"]))))
            s_ids = tok(r["output"], add_special_tokens=False)["input_ids"][:kk]
            ps.append((s_ids, rr[:kk], tok.decode(s_ids, skip_special_tokens=True),
                       tok.decode(rr[:kk], skip_special_tokens=True)))
        dv, ed = divergence(ps)
        gap = abs(dv - target)
        print(f"  tau={tau:<5} calib divergence={dv:.3f} (edit {ed:.3f})  gap={gap:.3f}",
              flush=True)
        if best is None or gap < best:
            best, chosen = gap, tau
    print(f"chosen tau={chosen} (gap {best:.3f}, tol {a.tol})", flush=True)
    if best > a.tol:
        print(f"WARNING: no temperature on the grid matches the treated prefix's "
              f"divergence within tol={a.tol}. The treated prefix cannot be mimicked "
              f"by an untreated model at any temperature on this grid, so the residual "
              f"is NOT estimable by this route. Report this; do not widen the grid post "
              f"hoc. Stage 2 (state refresh) then becomes the only separation of "
              f"content from provenance.", flush=True)

    t0 = time.time()
    recs = sample(model, tok, all_items[:a.n], max_new, stops, a.bs, chosen, seed=1234)
    # the corrupted reference is matched to ONE treated arm's divergence, so the
    # filename must name that arm: a single "corrupted_ref__f0.5" would collide
    # between interventions and silently pair the wrong control with the wrong arm.
    who = pathlib.Path(a.treated_run).name.split("__")
    arm = who[1] if len(who) > 1 else "unknown"
    out = (ROOT / "results" / "e12" / a.tag /
           f"{a.cell}__corrupted_ref__{arm}__f{a.frac:g}.jsonl")
    out.parent.mkdir(parents=True, exist_ok=True)
    header = {"_meta": True, "model": a.model, "cell": a.cell, "mask": "full",
              "kind": "corrupted_reference", "temperature": chosen,
              "match_stat": "1 - positional token agreement vs reference",
              "target_divergence": target, "target_char_edit": target_ed,
              "calib_gap": best, "matched_within_tol": bool(best <= a.tol), "tol": a.tol,
              "frac": a.frac, "treated_run": str(a.treated_run), "matched_arm": arm,
              "n_items": len(recs), "data_seed": 1234,
              "runtime_s": round(time.time() - t0, 1)}
    with open(out, "w") as f:
        f.write(json.dumps(header) + "\n")
        for r in recs:
            f.write(json.dumps(r) + "\n")
    print("wrote", out, flush=True)


if __name__ == "__main__":
    main()
