"""E12 — build the corrupted-reference trajectories Z~(0).

A two-arm clamp confounds "untreated" with "correct": the reference prefix Z(0) is the
full model's own correct trajectory.  Z~(0) is untreated but NOT correct, so that

    Y(R) - Y(R~)   is the part of the mediation explained by prefix CONTENT
    Y(R~) - Y(F)   is the residual attributable to the context having been produced
                   under the same perturbation, beyond its surface error content

Z~(0) is generated by the FULL-PRECISION model at temperature tau, so no treatment
touches it.  tau is calibrated so that the task-level error rate of the clamped span
matches that of the treated model's own prefix Z(T) to within `--tol`.

Task-level error, GSM8K: the span contains a calculator annotation `<<a op b=c>>`
whose stated result is wrong.  This matches error RATE, not error TYPE -- recorded as
a known limitation in E12_PREREGISTRATION.md §4, and the reason Stage 2 (state refresh)
is in the program rather than optional.

Calibration uses a held-out item split; the evaluation split is never used to pick tau.
"""
from __future__ import annotations
import argparse, json, pathlib, re, sys, time
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

import importlib.util
ROOT = pathlib.Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("run_eval", ROOT / "scripts" / "run_eval.py")
run_eval = importlib.util.module_from_spec(spec); spec.loader.exec_module(run_eval)
cspec = importlib.util.spec_from_file_location("clamp", ROOT / "scripts" / "run_e12_clamp.py")
clamp = importlib.util.module_from_spec(cspec); cspec.loader.exec_module(clamp)

CALC = re.compile(r"<<\s*([-\d\.\+\*/\(\) ,]+?)\s*=\s*(-?[\d\.,]+)\s*>>")


def span_has_error(text: str) -> bool:
    """True if any calculator annotation in the span states a wrong result."""
    for expr, stated in CALC.findall(text):
        try:
            got = eval(expr.replace(",", ""), {"__builtins__": {}}, {})
            if abs(float(got) - float(stated.replace(",", ""))) > 1e-6:
                return True
        except Exception:
            return True
    return False


def error_rate(texts) -> float:
    t = [x for x in texts if x]
    return sum(span_has_error(x) for x in t) / max(len(t), 1)


@torch.no_grad()
def sample(model, tok, items, max_new, stops, bs, temperature, seed):
    torch.manual_seed(seed)
    pad = tok.pad_token_id or tok.eos_token_id
    out = {}
    order = sorted(range(len(items)), key=lambda i: -len(items[i]["prompt"]))
    for s in range(0, len(order), bs):
        idxs = order[s:s + bs]
        enc = tok([items[i]["prompt"] for i in idxs], return_tensors="pt",
                  padding=True, padding_side="left").to(model.device)
        g = model.generate(**enc, max_new_tokens=max_new, do_sample=True,
                           temperature=temperature, top_p=1.0, top_k=0,
                           pad_token_id=pad)
        new = g[:, enc["input_ids"].shape[1]:]
        for j, i in enumerate(idxs):
            txt = tok.decode(new[j], skip_special_tokens=True)
            for st in stops:
                if st in txt:
                    txt = txt.split(st)[0]
            out[i] = {"id": items[i]["id"], "output": txt,
                      "n_new_tokens": int(new[j].shape[0]),
                      "gold": items[i]["gold"], "meta": items[i]["meta"]}
    return [out[i] for i in range(len(items))]


def treated_error_rate(path, k_frac, refs, tok):
    """error rate of the treated model's own prefix over the same clamped span"""
    texts = []
    for line in open(path):
        r = json.loads(line)
        if r.get("_meta"):
            continue
        ref = refs.get(r["id"])
        if not ref or ref["L0"] is None:
            continue
        k = int(round(k_frac * ref["L0"]))
        ids = tok(r.get("output", "") or "", add_special_tokens=False)["input_ids"][:k]
        texts.append(tok.decode(ids, skip_special_tokens=True))
    return error_rate(texts), len(texts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--tag", required=True)
    ap.add_argument("--cell", default="gsm8k_gen_cot")
    ap.add_argument("--treated-run", required=True,
                    help="the free-running treated run whose error rate is the target")
    ap.add_argument("--frac", type=float, default=0.5)
    ap.add_argument("--n", type=int, default=500)
    ap.add_argument("--calib-n", type=int, default=120, help="held-out split for tau")
    ap.add_argument("--bs", type=int, default=8)
    ap.add_argument("--tol", type=float, default=0.05)
    ap.add_argument("--grid", default="0.7,1.0,1.3,1.6,2.0")
    a = ap.parse_args()

    tok = AutoTokenizer.from_pretrained(a.model)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    model = AutoModelForCausalLM.from_pretrained(
        a.model, dtype=torch.bfloat16, device_map="cuda:0").eval()

    full_run = ROOT / "results" / "e01" / a.tag / f"{a.cell}__full.jsonl"
    refs = clamp.reference_table(tok, full_run, a.cell)
    target, n_t = treated_error_rate(a.treated_run, a.frac, refs, tok)
    print(f"target task-level error rate of the treated prefix "
          f"(frac={a.frac:g}): {target:.3f}  over {n_t} items", flush=True)

    # calibration split: items beyond the evaluation split, so tau is never fit on
    # the items the contrast is estimated on
    all_items = run_eval.load_items(a.cell, a.n + a.calib_n, 1234)
    calib = all_items[a.n:]
    max_new, stops = run_eval.CELL_GEN[a.cell]

    best, chosen = None, None
    for tau in [float(x) for x in a.grid.split(",")]:
        recs = sample(model, tok, calib, max_new, stops, a.bs, tau, seed=1234)
        spans = []
        for r in recs:
            ids = tok(r["output"], add_special_tokens=False)["input_ids"]
            L0 = clamp.answer_char_pos(a.cell, r["output"])
            kk = len(tok(r["output"][:L0], add_special_tokens=False)["input_ids"]) \
                if L0 is not None else len(ids)
            spans.append(tok.decode(ids[:int(round(a.frac * kk))], skip_special_tokens=True))
        er = error_rate(spans)
        gap = abs(er - target)
        print(f"  tau={tau:<5} calib error rate={er:.3f}  gap={gap:.3f}", flush=True)
        if best is None or gap < best:
            best, chosen = gap, tau
    print(f"chosen tau={chosen} (gap {best:.3f}, tol {a.tol})", flush=True)
    if best > a.tol:
        print(f"WARNING: no temperature on the grid reaches the target within tol. "
              f"The corrupted arm cannot be rate-matched here; report this rather "
              f"than widening the grid post hoc.", flush=True)

    t0 = time.time()
    recs = sample(model, tok, all_items[:a.n], max_new, stops, a.bs, chosen, seed=1234)
    out = ROOT / "results" / "e12" / a.tag / f"{a.cell}__corrupted_ref__f{a.frac:g}.jsonl"
    out.parent.mkdir(parents=True, exist_ok=True)
    header = {"_meta": True, "model": a.model, "cell": a.cell, "mask": "full",
              "kind": "corrupted_reference", "temperature": chosen,
              "target_error_rate": target, "calib_gap": best, "tol": a.tol,
              "frac": a.frac, "treated_run": str(a.treated_run),
              "n_items": len(recs), "data_seed": 1234,
              "runtime_s": round(time.time() - t0, 1)}
    with open(out, "w") as f:
        f.write(json.dumps(header) + "\n")
        for r in recs:
            f.write(json.dumps(r) + "\n")
    print("wrote", out, flush=True)


if __name__ == "__main__":
    main()
