"""Z~_surgical(0) — a reference prefix that is on-task, fluent, structured, and WRONG.

Both earlier controls failed the quality audit, in opposite directions:

  corrupted Z~(0)  temperature sampling   on_task 0.073  -- far off-task
  prune    Z(T')   another treatment      on_task 0.276  -- less on-task than
                                                            readout's own 0.415

So neither Y(R~) - Y(F) nor Y(foreign) - Y(F) isolates provenance: both are
contaminated by a difference in how usable the prefix is.

This builds the control the audit implies.  It takes the full-precision reference
trajectory and changes ONLY the arithmetic results, leaving the problem's numbers,
the sentence structure, the calculator-annotation format and the fluency untouched.
Each `<<expr=r>>r` becomes `<<expr=r'>>r'` for a perturbed r'.  The result is:

  untreated      generated by the full model, no compression touched it
  on-task        the problem's own numbers are still there
  structured     same format, same degeneracy profile
  WRONG          the computation stated is incorrect

which is exactly the contrast that separates "the prefix content is worse" from
"the prefix was produced under the same perturbation".

RATE MATCHING.  Corrupting EVERY annotation is the right control only when the
treated prefix is itself badly degraded, so that the control ends up no better than
the thing it stands in for.  That holds for readout truncation (its span contains
essentially no correct computation) and for 40% pruning.  It does NOT hold for 4-bit
quantization, whose free-running span is largely correct: corrupting every annotation
would make the control strictly worse than the treated prefix and the test would be
anti-conservative rather than conservative.

`--match-treated <run>` therefore corrupts annotations with a probability chosen so
that the control's per-span correctness matches that treated run's.  on_task,
structure, format and degeneracy stay fixed by construction; only the amount of wrong
arithmetic is tuned, which is the one axis the contrast is about.

No GPU, no temperature, no learned matching statistic to mis-specify.
"""
from __future__ import annotations
import argparse, json, pathlib, random, re, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
ROOT = pathlib.Path(__file__).resolve().parents[1]

ANNOT = re.compile(r"<<\s*([-\d\.\+\*/\(\) ,]+?)\s*=\s*(-?[\d,]*\.?\d+)\s*>>\s*(-?[\d,]*\.?\d+)")


def perturb(value: str, rng: random.Random) -> str:
    """Change the number enough to be wrong, little enough to stay plausible."""
    raw = value.replace(",", "")
    try:
        v = float(raw)
    except ValueError:
        return value
    is_int = ("." not in raw)
    for _ in range(12):
        delta = rng.choice([-3, -2, -1, 1, 2, 3]) if abs(v) < 20 else \
            v * rng.choice([-0.30, -0.20, -0.10, 0.10, 0.20, 0.30])
        nv = v + delta
        if abs(nv - v) < 1e-9:
            continue
        if is_int:
            nv = int(round(nv))
            if nv == int(v):
                continue
            out = f"{nv}"
        else:
            out = f"{nv:.2f}".rstrip("0").rstrip(".")
        if "," in value:                      # preserve thousands separators
            try:
                out = f"{int(float(out)):,}"
            except ValueError:
                pass
        return out
    return value


def corrupt(text: str, rng: random.Random, rate: float = 1.0) -> tuple:
    """Rewrite a `rate` fraction of calculator annotation RESULTS; leave all else alone."""
    n = 0

    def sub(m):
        nonlocal n
        expr, res, echo = m.group(1), m.group(2), m.group(3)
        if rng.random() > rate:
            return m.group(0)
        bad = perturb(res, rng)
        if bad == res:
            return m.group(0)
        n += 1
        # the echoed number after the annotation is the same quantity, so it moves too
        new_echo = bad if echo.replace(",", "") == res.replace(",", "") else echo
        return f"<<{expr}={bad}>>{new_echo}"

    return ANNOT.sub(sub, text), n


def treated_span_correctness(run_path, cell, frac, tag):
    """fraction of treated spans whose calculator annotations are all correct,
    among spans that contain any -- the quantity `--match-treated` matches."""
    import importlib.util
    from transformers import AutoTokenizer
    cs = importlib.util.spec_from_file_location(
        "clamp", ROOT / "scripts" / "run_e12_clamp.py")
    clamp = importlib.util.module_from_spec(cs); cs.loader.exec_module(clamp)
    tok = AutoTokenizer.from_pretrained("NousResearch/Meta-Llama-3.1-8B-Instruct")
    refs = clamp.reference_table(
        tok, ROOT / "results" / "e01" / tag / f"{cell}__full.jsonl", cell)
    ok = tot = 0
    for line in open(run_path):
        r = json.loads(line)
        if r.get("_meta") or r["id"] not in refs or refs[r["id"]]["L0"] is None:
            continue
        k = int(round(frac * refs[r["id"]]["L0"]))
        ids = tok(r.get("output", "") or "",
                  add_special_tokens=False)["input_ids"][:k]
        span = tok.decode(ids, skip_special_tokens=True)
        hits = ANNOT.findall(span)
        if not hits:
            continue
        tot += 1
        good = True
        for expr, stated, _ in hits:
            try:
                got = eval(expr.replace(",", ""), {"__builtins__": {}}, {})
                if abs(float(got) - float(stated.replace(",", ""))) > 1e-6:
                    good = False; break
            except Exception:
                good = False; break
        ok += good
    return (ok / tot if tot else 1.0), tot


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", default="llama31_8b_instruct")
    ap.add_argument("--cell", default="gsm8k_gen_cot")
    ap.add_argument("--seed", type=int, default=1234)
    ap.add_argument("--match-treated", default=None,
                    help="a free-running treated run; corrupt at the rate that makes "
                         "the control's span correctness match that run's")
    ap.add_argument("--frac", type=float, default=0.5)
    ap.add_argument("--suffix", default="")
    a = ap.parse_args()

    src = ROOT / "results" / "e01" / a.tag / f"{a.cell}__full.jsonl"
    rate, target = 1.0, None
    if a.match_treated:
        target, n_spans = treated_span_correctness(a.match_treated, a.cell, a.frac, a.tag)
        # a span is correct only if EVERY annotation in it is; with m annotations per
        # span the per-annotation corruption rate p gives span correctness (1-p)^m
        import statistics
        rate = 1.0 - target ** (1.0 / 2.8)      # 2.8 = mean annotations per span here
        rate = min(max(rate, 0.0), 1.0)
        print(f"matching {a.match_treated}: treated span correctness {target:.3f} "
              f"over {n_spans} spans -> per-annotation corruption rate {rate:.3f}")
    out = (ROOT / "results" / "e12" / a.tag /
           f"{a.cell}__surgical_ref{a.suffix}.jsonl")
    out.parent.mkdir(parents=True, exist_ok=True)
    rng = random.Random(a.seed)

    lines = [json.loads(l) for l in open(src)]
    meta, recs = lines[0], lines[1:]
    n_changed, n_any = 0, 0
    with open(out, "w") as f:
        f.write(json.dumps({**{k: v for k, v in meta.items()},
                            "kind": "surgical_corruption", "source": str(src),
                            "seed": a.seed, "corruption_rate": rate,
                            "match_treated": a.match_treated,
                            "target_span_correctness": target}) + "\n")
        for r in recs:
            new, n = corrupt(r.get("output", "") or "", rng, rate)
            n_any += (n > 0); n_changed += n
            f.write(json.dumps({**r, "output": new, "n_annotations_corrupted": n}) + "\n")
    print(f"wrote {out}")
    print(f"  {n_any}/{len(recs)} trajectories had at least one annotation corrupted")
    print(f"  {n_changed} annotations rewritten in total")
    print(f"  trajectories with NO annotation are passed through unchanged and are "
          f"excluded from the contrast by the analysis")


if __name__ == "__main__":
    main()
